/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package liveproject2;

/**
 *
 * @author Hp
 */
public class Operation_On_Student extends javax.swing.JPanel {

    /**
     * Creates new form Operation_On_Student
     */
    public static Admin_Home_Page adm1;
    public static Student_Admission std;
    public static Student_Admission2 std2;
    public static Student_Enquiry1 estd1;
    public static Student_Enquiry2 estd2;
    public static Student_Update upd;
    public Student_Delete sdel;
    public static void receiveInstanceOfAdminHomePage(Admin_Home_Page adm)
    {
        adm1=adm;
    }
    public static Admin_Home_Page sendInstanceOfAdminHomePage()
    {
        return adm1;
    }
    public static void receiveInstanceOfStudentAdmission2(Student_Admission2 std2)
    {
        Operation_On_Student.std2=std2;
    }
    public static void receiveInstatnceOfStudentEnquiry2(Student_Enquiry2 estd2)
    {
        Operation_On_Student.estd2=estd2;
    }
    public Operation_On_Student() {
        initComponents();
        std=new Student_Admission();
        estd1=new Student_Enquiry1();
        upd=new Student_Update();
        sdel=new Student_Delete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 0));

        jButton1.setFont(new java.awt.Font("Vani", 3, 18)); // NOI18N
        jButton1.setText("STUDENT ADMISSION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Vani", 3, 18)); // NOI18N
        jButton2.setText("STUDENT ENQUIRY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Vani", 3, 18)); // NOI18N
        jButton3.setText("UPDATE STUDENT DATA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Vani", 3, 18)); // NOI18N
        jButton4.setText("DELETE STUDENT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adm1.jPanel3.setVisible(false);
        upd.setVisible(false);
        std2.setVisible(false);
        sdel.setVisible(false);
        estd1.setVisible(false);
        estd2.setVisible(false);
        std.setVisible(true);
        Student_Enquiry1.returnInstance().setVisible(false);
        Student_Enquiry2.returnInstance().setVisible(false);
        Student_Update.returnInstance().setVisible(false);
        Student_Delete.returnInstance().setVisible(false);
        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(adm1.jPanel6);
        adm1.jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(std, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(std, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     adm1.jPanel3.setVisible(false);
        upd.setVisible(false);
        std2.setVisible(false);
        sdel.setVisible(false);
        std.setVisible(false);
        estd2.setVisible(false);
        estd1.setVisible(true);
        Student_Admission.returnInstance().setVisible(false);
        Student_Admission2.returnInstance().setVisible(false);
        Student_Update.returnInstance().setVisible(false);
        Student_Delete.returnInstance().setVisible(false);
        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(adm1.jPanel6);
        adm1.jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        adm1.jPanel3.setVisible(false);
        std.setVisible(false);
        std2.setVisible(false);
        sdel.setVisible(false);
        estd1.setVisible(false);
        estd2.setVisible(false);
        upd.setVisible(true);
        Student_Admission.returnInstance().setVisible(false);
        Student_Admission2.returnInstance().setVisible(false);
        Student_Enquiry1.returnInstance().setVisible(false);
        Student_Enquiry2.returnInstance().setVisible(false);
        Student_Delete.returnInstance().setVisible(false);
        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(adm1.jPanel6);
        adm1.jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        ); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        adm1.jPanel3.setVisible(false);
        std.setVisible(false);
        std2.setVisible(false);
        upd.setVisible(false);
        estd1.setVisible(false);
        estd2.setVisible(false);
        sdel.setVisible(true);
        Student_Admission.returnInstance().setVisible(false);
        Student_Admission2.returnInstance().setVisible(false);
        Student_Enquiry1.returnInstance().setVisible(false);
        Student_Enquiry2.returnInstance().setVisible(false);
        Student_Update.returnInstance().setVisible(false);
        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(adm1.jPanel6);
        adm1.jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sdel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sdel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );    
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
