/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package liveproject2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static liveproject2.Teacher_Update.adm1;
import oracle.jdbc.driver.OracleDriver;
/**
 *
 * @author Hp
 */
public class Teacher_Batch_Assign extends javax.swing.JPanel {

    /**
     * Creates new form Teacher_Batch_Assign
     */
    static Teacher_Batch_Assign adt;
    OracleDriver o;
    PreparedStatement s;
    ResultSet r;
    Connection co;
    public Teacher_Batch_Assign() {
        try {
            initComponents();
            adt=this;
           o=new oracle.jdbc.driver.OracleDriver();
           DriverManager.registerDriver(o);
          co=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","prashant");
          s=co.prepareStatement("select batch_id,start_time,end_time from batches where batch_id not in"
        + "(select batch_id from teachers_batches) order by subject_id");
          r=s.executeQuery();
            while(r.next())
            {
                Object batch_id=r.getString(1);
                Object start_time=r.getString(2);
                Object end_time=r.getString(3);
                Object item=batch_id + "(" + start_time + " to " + end_time + ")";
                jComboBox2.addItem(item);
                }
            r.close();
        } catch (Exception ex) {
            Logger.getLogger(Teacher_Batch_Assign.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }
    public static Teacher_Batch_Assign returnInstance()
    {
        adt.setAllComponentsStable();
        return adt;
    }
    public void setAllComponentsStable()
    {
        jTextField1.setText("");
        jComboBox1.removeAllItems();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("ASSIGN BATCH TO TEACHER");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter Teacher ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Batches assigned previously:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Select which batch to assign:");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jButton1.setText("ASSIGN BATCH ???");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(312, 312, 312))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        String teacher_id=jTextField1.getText();
        String batch_id_time=jComboBox2.getSelectedItem().toString();
        String subject=null;
        String start_time=null;
        String end_time=null;
        int check=1,flag=1;
        if(teacher_id.equals(""))
        {
       JOptionPane.showMessageDialog(adm1,"Please enter correct teacher ID","Batch Assignment Process",JOptionPane.WARNING_MESSAGE);     
        }
        else
        {
            try {
                OracleDriver od = new oracle.jdbc.driver.OracleDriver();
                DriverManager.registerDriver(od);
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","prashant");
                ResultSet rs2=DbConnection.select_all_batch_ids();
                String batch_id=null;
                while(rs2.next())
                {
                    if(batch_id_time.startsWith(rs2.getString(1)))
                    {
                        batch_id=batch_id_time.substring(0,rs2.getString(1).length());
                           PreparedStatement stmt2=conn.prepareStatement("select name,start_time,end_time from subjects,batches where batch_id=? and "
                                + "subjects.subject_id=batches.subject_id");
                        stmt2.setString(1,batch_id);
                        ResultSet rs4=stmt2.executeQuery();
                        while(rs4.next())
                        {
                            subject=rs4.getString(1);
                            start_time=rs4.getString(2);
                            end_time=rs4.getString(3);
                        }
                        rs4.close();
                        break;                            
                    }  
                } 
             int val=DbConnection.insert_into_teachers_batches(teacher_id, batch_id,subject,start_time,end_time);
             if(val>0)
             {
    JOptionPane.showMessageDialog(adm1,"Batch has been assigned successfully...","New Batch Assignment",JOptionPane.INFORMATION_MESSAGE);             
             }
             else
             {
    JOptionPane.showMessageDialog(adm1,"Sorry...Some problem has occured...Please try again","New Batch Assignment",JOptionPane.ERROR_MESSAGE);              
             }  
            } catch (Exception ex) {
                Logger.getLogger(Teacher_Batch_Assign.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    String teacher_id=jTextField1.getText();
        if(teacher_id.equals(""))
        {
       JOptionPane.showMessageDialog(adm1,"Please enter correct teacher ID","Batch Assignment Process",JOptionPane.WARNING_MESSAGE);     
        }
        else
        {
           
            try {
                int log=0;
                OracleDriver od = new oracle.jdbc.driver.OracleDriver();
                DriverManager.registerDriver(od);            
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","prashant");
                PreparedStatement stmt = conn.prepareStatement("select * from teacher_all_info");
   //             stmt.setString(1,teacher_id);
                ResultSet rs=stmt.executeQuery();
                while(rs.next())
                {
                    if(rs.getString(1).equals(teacher_id))
                    {
                        log=1;
                        break;
                    }   
                }
                stmt.close();
                rs.close();
                if(log==0)
                {
      JOptionPane.showMessageDialog(adm1,"Sorry,teacher ID not present in database...","Batch Assignment Process",JOptionPane.ERROR_MESSAGE);     
      jTextField1.setText("");
                }
               if(log==1)
               {
            PreparedStatement stmt1 = conn.prepareStatement("select teacher_id,batches.batch_id,batches.start_time,batches.end_time from "
                    + "teachers_batches,batches where teacher_id=? and teachers_batches.batch_id=batches.batch_id");   
            stmt1.setString(1,teacher_id);
            ResultSet rs1=stmt1.executeQuery();
            while(rs1.next())
            {
                String batch_id=rs1.getString(2);
                String start_time=rs1.getString(3);
                String end_time=rs1.getString(4);
                Object item=batch_id+"("+start_time+" to "+end_time+")";
                jComboBox1.addItem(item);
            }
            rs1.close();
               }
            }
            catch(Exception e){}
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
